#!/usr/bin/env python3
"""Write the per-overlay splat configs and config/overlays.txt (T-0008).

Usage (inside Docker): tools/docker.sh python3 tools/gen_overlay_configs.py

For every disc/files/CDROM/EXEDIR/*.EXN this finds the end of the code (last
`jr $ra` plus its delay slot) and writes config/overlays/<NAME>.yaml: one code
segment (C-capable, IDO) up to that point, then the rest of the 0x30000-byte
file (rodata, data, checksum trailer) as one rodata segment.
config/overlays.txt lists `<NAME> <load address> <text size>` for configure.py.
Load addresses: wiki/overlays.md. O.BIN is not code and is skipped.
"""
import glob
import hashlib
import os
import struct
import sys

DIR = "disc/files/CDROM/EXEDIR"
SIZE = 0x30000
DEFAULT_BASE = 0x80132000
# Overlays whose jal targets only line up at another address (wiki/overlays.md).
BASE = {"EVENT": 0x800F6000, "GYOZI": 0x80134000}

# Per-overlay symbol files (config/overlays/<NAME>_symbols.txt), kept by hand.
# DATE starts with a lone `nop` before its entry function, which asm-processor
# rejects as a function of its own; the symbol file gives the entry function
# its full size (up to the next function) so the nop stays part of it.
EXTRA_SYMS = {"DATE": "func_80132000 = 0x80132000; // type:func size:0x288\n"}

TEMPLATE = """# splat config for the overlay {name}.EXN (T-0008). Generated by
# tools/gen_overlay_configs.py; load address and layout: wiki/overlays.md.
name: ovl_{name}
sha1: {sha1}
options:
  basename: {name}
  target_path: {dir}/{name}.EXN
  elf_path: build/ovl/{name}.elf
  base_path: ../..
  platform: psx
  compiler: PSYQ

  asm_path: asm/ovl/{name}
  src_path: src/ovl
  build_path: build/ovl/{name}

  create_asm_dependencies: True

  ld_script_path: build/ovl/{name}.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x0

  o_as_suffix: True
  use_legacy_include_asm: False
  # splat would overwrite the hand-maintained include/*.h and macro.inc (T-0013)
  generate_asm_macros_files: False
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  asm_end_label: endlabel

  section_order: [".text", ".rodata", ".data", ".bss"]
  auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.txt{extra}
  reloc_addrs_path:
    - config/reloc_addrs.txt
  undefined_funcs_auto_path: build/ovl/{name}_undefined_funcs_auto.txt
  undefined_syms_auto_path: build/ovl/{name}_undefined_syms_auto.txt

  subalign: 2
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: {name}
    type: code
    start: 0x0
    vram: 0x{base:08X}
    subsegments:
      - [0x0, c, {name}]
      - [0x{text:X}, rodata, {name}_rodata]
  - [0x{size:X}]
"""


def main():
    rows = []
    for path in sorted(glob.glob(DIR + "/*.EXN")):
        name = os.path.basename(path)[:-4]
        data = open(path, "rb").read()
        if len(data) != SIZE:
            sys.exit("%s: unexpected size %d" % (path, len(data)))
        words = struct.unpack("<%dI" % (SIZE // 4), data)
        last_jr = max(i for i, x in enumerate(words) if x == 0x03E00008)
        text = (last_jr + 2) * 4
        text = (text + 15) & ~15  # the linker aligns sections to 16
        if any(data[(last_jr + 2) * 4:text]):
            print("%s: non-zero bytes in the alignment gap" % name)
        base = BASE.get(name, DEFAULT_BASE)
        sha1 = hashlib.sha1(data).hexdigest()
        with open("config/overlays/%s.yaml" % name, "w") as f:
            extra = ""
            if name in EXTRA_SYMS:
                extra = "\n    - config/overlays/%s_symbols.txt" % name
                with open("config/overlays/%s_symbols.txt" % name, "w") as g:
                    g.write(EXTRA_SYMS[name])
            f.write(TEMPLATE.format(name=name, base=base, text=text, extra=extra,
                                    size=SIZE, dir=DIR, sha1=sha1))
        with open("config/overlays/%s.sha1" % name, "w") as f:
            f.write("%s  %s.EXN\n" % (sha1, name))
        rows.append("%s 0x%08X 0x%X" % (name, base, text))
    with open("config/overlays.txt", "w") as f:
        f.write("# name load_address text_size (tools/gen_overlay_configs.py)\n")
        f.write("\n".join(rows) + "\n")


if __name__ == "__main__":
    sys.exit(main())
