"""Unit tests for tools/rodata_pieces.py and tools/rodata_island.py (T-1340) on synthetic splat
output (no game data).

Run from tools/: python3 test_rodata_tools.py   (inside Docker: tools/docker.sh sh -c 'cd tools && python3 test_rodata_tools.py')
"""
import os
import subprocess
import sys
import tempfile
import unittest

import rodata_island
import rodata_pieces

HEADER = '.include "macro.inc"\n\n.section .rodata, "a"\n\n/* Generated by spimdisasm 1.42.4 */\n\n'


def string_block(sym, off, text):
    return ('.align 2\nnonmatching %s\n\ndlabel %s\n    /* %X %08X */ .asciz "%s"\n    /* 00 */\n'
            '.align 2\nenddlabel %s\n\n' % (sym, sym, off, 0x80100000 + off, text, sym))


def table_block(sym, off, targets, pad=0):
    words = ["    /* %X %08X 00000000 */ .word %s\n" % (off + 4 * i, 0x80100000 + off + 4 * i, t)
             for i, t in enumerate(targets)]
    words += ["    /* %X %08X 00000000 */ .word 0x00000000\n" % (off + 4 * (len(targets) + i),
                                                                 0x80100000 + off + 4 * (len(targets) + i))
              for i in range(pad)]
    return ("nonmatching %s\n\ndlabel %s\n%senddlabel %s\n\n" % (sym, sym, "".join(words), sym))


# Two objects. Object A at 0x00: a string, a 5-word and a 4-word table, 4 bytes of
# padding (to 0x30). Object B at 0x30: a string and one table of 5 words, 4 bytes of padding (to 0x50).
LABELS = [".L1", ".L2", ".L3", ".L4", ".L5"]
RODATA = (HEADER + string_block("D_80100000", 0x0, "hello")
          + table_block("jtbl_80100008", 0x8, LABELS)
          + table_block("jtbl_8010001C", 0x1C, LABELS[:4], pad=1)
          + string_block("D_80100030", 0x30, "world")
          + table_block("jtbl_80100038", 0x38, LABELS, pad=1))


class SplitBlocks(unittest.TestCase):
    def test_blocks_keep_alignment_and_names(self):
        blocks = rodata_pieces.split_blocks(RODATA)
        self.assertEqual([s for s, _ in blocks],
                         ["D_80100000", "jtbl_80100008", "jtbl_8010001C", "D_80100030", "jtbl_80100038"])
        self.assertTrue(blocks[0][1].startswith(".align 2\nnonmatching D_80100000"))

    def test_unterminated_block_fails(self):
        with self.assertRaises(ValueError):
            rodata_pieces.split_blocks(HEADER + "nonmatching X\n\ndlabel X\n .word 1\n")


class Clean(unittest.TestCase):
    def test_table_loses_align_and_padding_words(self):
        body = ".align 3\n" + table_block("jtbl_80100008", 0x8, LABELS, pad=2)
        out = rodata_pieces.clean("jtbl_80100008", body)
        self.assertNotIn(".align", out)
        self.assertEqual(out.count(".word"), 5)

    def test_string_is_shift_jis_escaped(self):
        body = string_block("D_80100000", 0, "試")
        out = rodata_pieces.clean("D_80100000", body)
        self.assertNotIn("試", out)
        self.assertIn('"\\', out)


class Distribute(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.folder = os.path.join(self.tmp.name, "nonmatchings", "X")
        os.makedirs(self.folder)

    def tearDown(self):
        self.tmp.cleanup()

    def func(self, name, vram, refs):
        text = "nonmatching %s, 0x8\n\nglabel %s\n    /* 0 %08X 00000000 */  lui $t6, %%hi(%s)\nendlabel %s\n" % (
            name, name, vram, refs, name)
        with open(os.path.join(self.folder, name + ".s"), "w") as f:
            f.write(text)

    def test_symbols_go_to_lowest_function_that_mentions_them(self):
        self.func("func_B", 0x80200100, "jtbl_80100008")
        self.func("func_A", 0x80200000, "D_80100000")
        src = os.path.join(self.tmp.name, "X.rodata.s")
        with open(src, "w") as f:
            f.write(HEADER + string_block("D_80100000", 0, "hello")
                    + table_block("jtbl_80100008", 8, LABELS) + table_block("jtbl_8010001C", 0x1C, LABELS))
        pieces = os.path.join(self.tmp.name, "X.rodata")
        n, free = rodata_pieces.process(src, self.folder, pieces)
        self.assertEqual((n, free), (2, ["jtbl_8010001C"]))
        a = open(os.path.join(self.folder, "func_A.s")).read()
        b = open(os.path.join(self.folder, "func_B.s")).read()
        self.assertIn(".section .rodata\n", a)
        self.assertNotIn(".late_rodata", a)
        self.assertIn(".section .late_rodata\n", b)
        self.assertTrue(os.path.exists(os.path.join(pieces, "jtbl_8010001C.s")))

    def test_second_run_gives_the_same_files(self):
        self.func("func_A", 0x80200000, "D_80100000")
        src = os.path.join(self.tmp.name, "X.rodata.s")
        with open(src, "w") as f:
            f.write(HEADER + string_block("D_80100000", 0, "hello"))
        pieces = os.path.join(self.tmp.name, "X.rodata")
        rodata_pieces.process(src, self.folder, pieces)
        first = open(os.path.join(self.folder, "func_A.s")).read()
        rodata_pieces.process(src, self.folder, pieces)
        self.assertEqual(open(os.path.join(self.folder, "func_A.s")).read(), first)

    def test_prefix_symbol_name_is_not_a_match(self):
        self.func("func_A", 0x80200000, "D_801000000")
        src = os.path.join(self.tmp.name, "X.rodata.s")
        with open(src, "w") as f:
            f.write(HEADER + string_block("D_80100000", 0, "hello"))
        n, free = rodata_pieces.process(src, self.folder, os.path.join(self.tmp.name, "p"))
        self.assertEqual((n, free), (0, ["D_80100000"]))


class FindChunk(unittest.TestCase):
    def setUp(self):
        self.blocks = rodata_pieces.split_blocks(RODATA)

    def test_first_object(self):
        self.assertEqual(rodata_island.find_chunk(self.blocks, ["jtbl_80100008"]), (0x0, 0x30))

    def test_second_object_starts_after_padding(self):
        self.assertEqual(rodata_island.find_chunk(self.blocks, ["jtbl_80100038"]), (0x30, 0x50))

    def test_tables_of_two_objects_are_refused(self):
        with self.assertRaises(ValueError):
            rodata_island.find_chunk(self.blocks, ["jtbl_8010001C", "jtbl_80100038"])

    def test_unknown_table_is_refused(self):
        with self.assertRaises(ValueError):
            rodata_island.find_chunk(self.blocks, ["jtbl_DEADBEEF"])


class Cli(unittest.TestCase):
    def test_yaml_rewrite_and_second_island_refused(self):
        tools = os.path.dirname(os.path.abspath(__file__))
        with tempfile.TemporaryDirectory() as tmp:
            os.makedirs(os.path.join(tmp, "asm", "data"))
            os.makedirs(os.path.join(tmp, "asm", "nonmatchings", "X"))
            with open(os.path.join(tmp, "asm", "data", "rodata.rodata.s"), "w") as f:
                f.write(RODATA)
            with open(os.path.join(tmp, "asm", "nonmatchings", "X", "func_A.s"), "w") as f:
                f.write("glabel func_A\n lui $t6, %hi(jtbl_80100038)\n lw $t6, %lo(jtbl_80100038)($at)\n")
            with open(os.path.join(tmp, "c.yaml"), "w") as f:
                f.write("options:\n  asm_path: asm\nsegments:\n  - name: main\n    subsegments:\n"
                        "      - [0x0, c, X]\n      - [0x0, rodata, rodata]\n      - [0x200, data, data]\n")
            run = [sys.executable, os.path.join(tools, "rodata_island.py"), "c.yaml", "X", "func_A"]
            subprocess.run(run, cwd=tmp, check=True, stdout=subprocess.PIPE)
            text = open(os.path.join(tmp, "c.yaml")).read()
            self.assertIn("[0x0, rodata, rodata]", text)
            self.assertIn("[0x30, .rodata, X]", text)
            self.assertIn("[0x50, rodata, rodata_after_X]", text)
            again = subprocess.run(run, cwd=tmp, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            self.assertNotEqual(again.returncode, 0)


if __name__ == "__main__":
    unittest.main()
